export const projects = [
  {
    id: "1111111111",
    images: "pr1.jpg",
    title: "Car Project",
    project: "Website(Front-End)",
    client: "Tegeta",
    duration: "4 Month(With Team)",
    framework: "Next JS",
    link: "https://www.tegetaapproved.ge/en",
  },
  {
    id: "11111118671",
    images: "pr2.jpg",
    title: "Retail project",
    project: "Website",
    client: "Capital Group",
    duration: "1 Month",
    framework: "React JS",
    link: "https://cptlgroup.ge/",
  },
  {
    id: "1451111111",
    images: "pr3.jpg",
    title: "MovieQuote Project",
    project: "Website",
    client: "Training",
    duration: "1 Month",
    framework: "React/Node",
    link: "https://movie-quote-uaxr.vercel.app/dashboard",
  },
];
